### PR TITLE
add Static Application Security Testing behind 'security-sast'

### PR DESCRIPTION
**Pull request by tsunammis**
Hello,

The idea of this pull-request is to add a bit of security testing in **Gazr**. The first step is to add **"SAST"** _(Static Application Security Testing)_.

More details [on the gitlab documentation](https://docs.gitlab.com/ee/user/project/merge_requests/sast.html).

I suggest putting this static analysis behind `make security-sast`

What do you think @tyrcho @Djiit @kerphi ?

### CODE REVIEW

**Comment by Djiit** [comment]
As it is becoming more and more adopted, it should be part of the proposed spec ! +1

**Comment by achedeuzot** [comment]
Why not just `security` ? And then everyone can have various specialized security tests?

For example, the `test` recipe has various `test-something` that can be custom. 
So in the same spirit, I would see a `security` recipe with sub-recipes of `security-sast` or `security-.... `.

**Comment by tsunammis** [comment]
@achedeuzot According to me, just `security` is too generic. `sast` describes static analysis. We can imagine in the future to integrate `dast` _(Dynamic Application Security Testing)_.

Thus, a task to launch `all` the security tasks (like `test` is for testing).

```makefile
security: security-sast security-dast
    true

security-sast:
    true

security-dast:
    true 
```

@achedeuzot what do you think?

**Comment by achedeuzot** [comment]
@stan Yep, that's what I meant so :+1:

**Comment by abusi** [comment]
I like it too. 
IMHO Sast is complementary with lynt/style/format as its reads the code as opposed as testing/dast that will execute the code. I'll link it with this part of the spec instead of the test part, but i'm all in for adding sast (and dast in the future) to the spec.

**Pull request merged**
